//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferWebAPI.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferCatLocMap
    {
        public long ID { get; set; }
        public long CategoryID { get; set; }
        public long LocationID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual OfferCategory OfferCategory { get; set; }
        public virtual OfferLocation OfferLocation { get; set; }
    }
}
