//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferWebAPI.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferAvailOutlet
    {
        public long ID { get; set; }
        public long OfferId { get; set; }
        public long OutletID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
    
        public virtual OfferLocOutletMap OfferLocOutletMap { get; set; }
        public virtual OffersInfo OffersInfo { get; set; }
    }
}
