//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferWebAPI.EntityDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OFFERDBEntities1 : DbContext
    {
        public OFFERDBEntities1()
            : base("name=OFFERDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OfferAvailOutlet> OfferAvailOutlets { get; set; }
        public virtual DbSet<OfferCategory> OfferCategories { get; set; }
        public virtual DbSet<OfferCatLocMap> OfferCatLocMaps { get; set; }
        public virtual DbSet<OfferLocation> OfferLocations { get; set; }
        public virtual DbSet<OfferLocOutletMap> OfferLocOutletMaps { get; set; }
        public virtual DbSet<OfferReview> OfferReviews { get; set; }
        public virtual DbSet<OffersInfo> OffersInfoes { get; set; }
        public virtual DbSet<OfferView> OfferViews { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SysEnum> SysEnums { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
        public virtual DbSet<OfferFeedback> OfferFeedbacks { get; set; }
    }
}
